import fs from "node:fs";
import path from "node:path";
import OverviewClient from "./OverviewClient";

export const metadata = {
  title: "OncoLens: a RAG system over the oncology literature",
  description:
    "Search oncology papers by concept, get the exact passage, and compare papers on "
    + "the same technical dimensions. Every published number has a command that produces it.",
};

function readJson(name: string) {
  try {
    return JSON.parse(
      fs.readFileSync(path.join(process.cwd(), "public", name), "utf-8"));
  } catch {
    return null;
  }
}

export default function OverviewPage() {
  // Both artifacts are generated by scripts, never hand-written. A missing one renders as
  // absent rather than as a placeholder — the same rule the evaluation follows.
  return <OverviewClient journey={readJson("journey.json")} clusters={readJson("clusters.json")} />;
}
